import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Icon } from '../components';
import { validateRequired } from '../utils/validation';
import { downloadTextFile } from '../utils/actions';

export function StatusBadge({ status }) {
  const key = String(status || 'Draft').toLowerCase().replace(/\s+/g, '-');
  return <span className={`ems-status ems-status--${key}`}>{status}</span>;
}

export function PageHeader({ title, description, actions }) {
  return (
    <div className="ems-page-header">
      <div>
        <h1>{title}</h1>
        <p>{description}</p>
      </div>
      {actions && <div className="ems-page-actions">{actions}</div>}
    </div>
  );
}

export function Breadcrumbs({ items }) {
  return (
    <nav className="ems-breadcrumbs" aria-label="Breadcrumb">
      <span>EMS</span>
      {items.map((item) => (
        <React.Fragment key={item}>
          <Icon name="chevronRight" size={14} />
          <span>{item}</span>
        </React.Fragment>
      ))}
    </nav>
  );
}

export function Card({ title, subtitle, icon, children, actions }) {
  return (
    <section className="ems-card">
      {(title || actions) && (
        <div className="ems-card-head">
          <div>
            {title && <h2>{icon && <Icon name={icon} size={18} />} {title}</h2>}
            {subtitle && <p>{subtitle}</p>}
          </div>
          {actions && <div className="ems-card-actions">{actions}</div>}
        </div>
      )}
      {children}
    </section>
  );
}

export function ModuleCard({ module }) {
  return (
    <Link className="ems-module-card" to={module.route}>
      <span className="ems-module-icon"><Icon name={module.icon} size={22} /></span>
      <span className="ems-module-ref">{module.ref}</span>
      <h2>{module.title}</h2>
      <p>{module.description}</p>
      <strong>{module.pending} pending tasks</strong>
    </Link>
  );
}

export function DataTable({ columns, rows, statusColumn }) {
  const [message, setMessage] = useState('');

  const runCellAction = (cell) => {
    const label = String(cell);
    if (/download|pdf|excel/i.test(label)) {
      downloadTextFile(`${label.replace(/\s+/g, '-').toLowerCase()}.txt`, `${label}\nGenerated by MTPG & RIHS portal placeholder.`);
      setMessage(`${label} downloaded.`);
    } else {
      setMessage(`${label} action completed.`);
    }
  };

  return (
    <>
      {message && <div className="ems-action-message">{message}</div>}
      <div className="ems-table-shell">
        <table className="ems-data-table">
          <thead>
            <tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr>
          </thead>
          <tbody>
            {rows.map((row, rowIndex) => (
              <tr key={`${rowIndex}-${row[0]}`}>
                {row.map((cell, cellIndex) => {
                  const actionCell = /download|review/i.test(String(cell));
                  return (
                    <td className={cellIndex === statusColumn ? 'ems-status-cell' : actionCell ? 'ems-action-cell' : undefined} key={`${cellIndex}-${cell}`}>
                      {cellIndex === statusColumn ? (
                        <StatusBadge status={cell} />
                      ) : actionCell ? (
                        <button className="ems-table-action" type="button" onClick={() => runCellAction(cell)}>{cell}</button>
                      ) : cell}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </>
  );
}

export function FormField({ label, name, value, onChange, options, type = 'text', required, placeholder }) {
  return (
    <label className="ems-form-field">
      <span>{label}{required ? ' *' : ''}</span>
      {options ? (
        <select name={name} value={value} onChange={onChange} required={required}>
          <option value="">Select {label}</option>
          {options.map((option) => <option key={option} value={option}>{option}</option>)}
        </select>
      ) : (
        <input name={name} type={type} value={value} onChange={onChange} required={required} placeholder={placeholder || label} />
      )}
    </label>
  );
}

export function ValidatedForm({ fields, initialValues = {}, submitLabel = 'Save Draft', onSubmit, children }) {
  const [values, setValues] = useState(() => fields.reduce((acc, field) => ({ ...acc, [field.name]: initialValues[field.name] || '' }), {}));
  const [errors, setErrors] = useState({});
  const [message, setMessage] = useState('');

  const handleChange = (event) => {
    const { name, value } = event.target;
    setValues((current) => ({ ...current, [name]: value }));
    setErrors((current) => ({ ...current, [name]: '' }));
  };

  const requiredFields = useMemo(() => fields.filter((field) => field.required), [fields]);

  const handleSubmit = (event) => {
    event.preventDefault();
    const nextErrors = validateRequired(values, requiredFields);
    setErrors(nextErrors);
    if (Object.keys(nextErrors).length === 0) {
      onSubmit?.(values);
      setMessage(`${submitLabel} completed.`);
    }
  };

  return (
    <form className="ems-form" onSubmit={handleSubmit}>
      {message && <div className="ems-action-message">{message}</div>}
      <div className="ems-form-grid">
        {fields.map((field) => (
          <div key={field.name}>
            <FormField {...field} value={values[field.name]} onChange={handleChange} />
            {errors[field.name] && <small className="ems-form-error">{errors[field.name]}</small>}
          </div>
        ))}
      </div>
      {children}
      <button className="ems-btn ems-btn-primary" type="submit"><Icon name="checkCircle" size={16} /> {submitLabel}</button>
    </form>
  );
}

export function UploadControl({ title, detail = 'PDF format required where mandated by institutional rules', required }) {
  const [fileName, setFileName] = useState('');

  return (
    <div className="ems-upload-control">
      <Icon name="upload" size={20} />
      <strong>{title}{required ? ' *' : ''}</strong>
      <span>{detail}</span>
      <label className="ems-upload-button">
        <Icon name="filePlus" size={15} /> Choose File
        <input
          type="file"
          accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png"
          onChange={(event) => setFileName(event.target.files?.[0]?.name || '')}
        />
      </label>
      {fileName && <small>{fileName}</small>}
    </div>
  );
}

export function ApprovalWorkflow({ title = 'Approval Workflow', dsc = false }) {
  const steps = ['Draft', 'Submitted', 'Verified', 'Approved'];
  const [status, setStatus] = useState('Submitted');

  return (
    <div className="ems-approval">
      <div className="ems-approval-title">
        <strong>{title}</strong>
        {dsc && <span><Icon name="shield" size={14} /> DSC required</span>}
      </div>
      <div className="ems-workflow-line">
        {steps.map((step, index) => (
          <div key={step} className="ems-workflow-step">
            <span>{index + 1}</span>
            <strong>{step}</strong>
          </div>
        ))}
      </div>
      <div className="ems-action-row">
        <button className="ems-btn ems-btn-primary" type="button" onClick={() => setStatus('Verified')}>Verify</button>
        <button className="ems-btn ems-btn-secondary" type="button" onClick={() => setStatus('Sent Back')}>Send Back</button>
        <button className="ems-btn ems-btn-danger" type="button" onClick={() => setStatus('Rejected')}>Reject</button>
      </div>
      <div className="ems-action-message">Workflow status: {status}</div>
    </div>
  );
}

export function FilterBar({ filters }) {
  const [values, setValues] = useState(() => filters.reduce((acc, filter) => ({ ...acc, [filter.name]: '' }), {}));
  const [message, setMessage] = useState('');

  const handleChange = (event) => {
    const { name, value } = event.target;
    setValues((current) => ({ ...current, [name]: value }));
  };

  return (
    <div className="ems-filter-bar">
      {filters.map((filter) => (
        <FormField key={filter.name} {...filter} value={values[filter.name]} onChange={handleChange} />
      ))}
      <button className="ems-btn ems-btn-primary" type="button" onClick={() => setMessage('Filters applied to report preview.')}><Icon name="filter" size={15} /> Apply Filters</button>
      {message && <div className="ems-action-message">{message}</div>}
    </div>
  );
}

export function AlertStrip({ children, tone = 'warning' }) {
  return <div className={`ems-alert ems-alert--${tone}`}><Icon name="alertTriangle" size={16} /> {children}</div>;
}
