export const studentModel = {
  dprSection: 'Workflow 4.1 Student Module',
  requirements: [
    { ref: 1, title: 'Entry of basic details', screen: 'Student Draft', complexity: 'Medium', manDays: 16 },
    { ref: 2, title: 'Upload student proof documents', screen: 'Proof Documents', complexity: 'Medium', manDays: 8 },
    { ref: 3, title: 'Entry of education details', screen: 'Education Details', complexity: 'High', manDays: 24 },
    { ref: 4, title: 'Upload education PDFs', screen: 'Education Details', complexity: 'Medium', manDays: 8 },
    { ref: 5, title: 'Verification and approval of student details', screen: 'Data Verification', complexity: 'High', manDays: 24 },
    { ref: 6, title: 'Generate unique student registration number', screen: 'Data Verification', complexity: 'Low', manDays: 4 },
  ],
  basicFields: [
    'Name of Student',
    'Date of Birth',
    'E-Mail ID',
    'Mobile Number',
    'Student ID',
    'Name of Father',
    'Name of Mother',
    'Address',
    'Place of Residence',
    'State',
    'Pin Code',
  ],
  educationFields: [
    'Education Level',
    'Major Subjects',
    'Name of Board / Exam',
    'Name of School / College',
    'Address of School / College',
    'Place',
    'Pin Code',
    'Year of Passing',
    'Total Marks',
    'Marks Obtained',
    'Grade / Percentage',
    'Student Registration Number',
    'Certificate Serial Number',
  ],
  proofDocuments: ['Name proof', 'Date of Birth proof', 'Student ID proof', 'Address proof'],
  workflow: ['College data entry', 'Board verification', 'Approve / reject / send back', 'Digital signature', 'Registration number generation'],
};

export const validationRules = [
  'Mandatory fields completed before submit',
  'Email and mobile format check',
  'PIN code must be 6 digits',
  'DOB cannot be future date and must meet eligibility rules',
  'Year of passing cannot exceed current year',
  'Marks obtained must be less than or equal to total marks',
  'Percentage or grade must match marks entered',
  'Mandatory PDF uploads checked by size and type',
  'Effective start date must be before end date',
  'Duplicate student ID or registration number blocked',
  'Attendance must exist before marks entry',
  'Marks entry blocked for absent students',
];

export const students = [
  {
    id: 'STU-1024',
    name: 'Kavitha R',
    dob: '2004-08-12',
    email: 'kavitha@example.com',
    mobile: '9876543211',
    college: 'MTPG&RIHS',
    course: 'B.Sc. Nursing',
    term: 'Term 2',
    status: 'Checker Review',
    registrationNo: '-',
  },
  {
    id: 'STU-1025',
    name: 'Mohan Das',
    dob: '2003-11-02',
    email: 'mohan@example.com',
    mobile: '9876543212',
    college: 'JIPMER',
    course: 'BPT',
    term: 'Final Term',
    status: 'Approved',
    registrationNo: 'MTP-2026-00082',
  },
  {
    id: 'STU-1026',
    name: 'Anitha P',
    dob: '2005-01-19',
    email: 'anitha@example.com',
    mobile: '9876543213',
    college: 'MGMC',
    course: 'B.Pharm',
    term: 'Term 1',
    status: 'Sent Back',
    registrationNo: '-',
  },
];

export const educationRows = [
  ['Higher Secondary', '2022', '600', '516', '86%', 'TN-HSC-7781', 'CERT-10091', 'PDF Uploaded'],
  ['Diploma', '2023', '800', '672', '84%', 'DIP-45120', 'CERT-20441', 'PDF Pending'],
];
